start_molecule = None #'CCn1c(Sc2ncnc3onc(C)c23)nnc1N1CCOCC1'
epsilon_start = 1.0
epsilon_end = 0.01
epsilon_decay = 2000
optimizer = "Adam"
polyak = 0.995
atom_types = ["C", "O", "N"]
num_episodes = 10000 
max_steps_per_episode = 40
allow_removal = True
allow_no_modification = True
allow_bonds_between_rings = False
allowed_ring_sizes = [3, 4, 5, 6]
replay_buffer_size =5000
learning_rate = 1e-4
gamma = 0.95
fingerprint_radius = 3
fingerprint_length = 2048
discount_factor = 0.9
batch_size = 128 
learning_frequency = 4
update_frequency = 20                
save_frequency = 200                 
# reward_fn = "ba_score"
# constraint_type = "qed"
reward_type = "BA"
num_bootstrap_heads = False
#ANDB = True
multi_obj = False
multi_obj_weight = 0.0
reward_sign = 1
MODEL_PATH = "./model_saved/ba/"
SAVE_PATH = "./results_saved/ba/"
